import SideBar from "@/Components/SideBar";
import "./globals.css";



export const metadata = {
  title: "Golam Sarwar | Full-stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div><SideBar/></div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
